# Generated by Django 5.0.7 on 2024-10-06 12:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('form', models.CharField(choices=[('S', 'Simple Form'), ('H', 'Hiring Form')], default='S', max_length=1)),
                ('logged', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='HiringForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(blank=True, max_length=225, null=True)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.DecimalField(decimal_places=0, max_digits=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forms.pdf')),
            ],
        ),
    ]
