# Generated by Django 5.1.1 on 2024-10-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='form',
            field=models.CharField(choices=[('S', 'Simple Forms'), ('H', 'Hiring Forms')], default='S', max_length=1),
        ),
    ]
