# Generated by Django 5.0.6 on 2024-05-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_alter_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseattributes',
            name='attribute',
            field=models.TextField(),
        ),
    ]
