# Generated by Django 5.0.6 on 2024-05-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_alter_courseattributes_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_uploaded'),
        ),
    ]
