# Generated by Django 5.0.6 on 2024-06-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0005_course_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prereg',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
