# Generated by Django 5.0.7 on 2024-07-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0006_alter_prereg_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='about_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='about_fa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_fa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='last_update_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='last_update_fa',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='slug_en',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='slug_fa',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers_en',
            field=models.ManyToManyField(null=True, related_name='courses', to='default.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers_fa',
            field=models.ManyToManyField(null=True, related_name='courses', to='default.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='video_en',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_fa',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded'),
        ),
        migrations.AddField(
            model_name='course',
            name='view_count_en',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='view_count_fa',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
