# Generated by Django 5.0.7 on 2024-08-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0009_alter_course_options_alter_courseattributes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.TextField(blank=True, null=True, verbose_name='ویدیو'),
        ),
    ]
