# Generated by Django 5.1.1 on 2024-10-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0010_alter_course_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
