# Generated by Django 5.1.1 on 2024-10-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0011_alter_course_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseattributes',
            name='gif',
            field=models.FileField(default=1, upload_to='gifs_uploaded', verbose_name='گیف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
