# Generated by Django 5.1.1 on 2024-10-14 11:11

import default.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0012_courseattributes_gif_alter_course_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseattributes',
            name='gif',
            field=models.FileField(upload_to='gifs_uploaded', validators=[default.validators.validate_big_file_size], verbose_name='گیف'),
        ),
    ]
