# Generated by Django 5.1.1 on 2024-10-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0013_alter_courseattributes_gif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseattributes',
            name='gif',
        ),
    ]
