# Generated by Django 5.1.1 on 2024-10-14 11:15

import default.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0014_remove_courseattributes_gif'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseattributes',
            name='gif',
            field=models.FileField(blank=True, null=True, upload_to='gifs_uploaded', validators=[default.validators.validate_big_file_size], verbose_name='گیف'),
        ),
    ]
