# Generated by Django 5.1.1 on 2024-10-19 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0015_courseattributes_gif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='roadmap',
            field=models.ImageField(blank=True, null=True, upload_to='images_uploaded', verbose_name='رودمپ'),
        ),
        migrations.AddField(
            model_name='course',
            name='gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='default.gift', verbose_name='هدیه دوره'),
        ),
    ]
