# Generated by Django 5.1.1 on 2024-10-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0016_gift_course_roadmap_course_gift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'verbose_name': 'هدیه', 'verbose_name_plural': 'هدایا'},
        ),
    ]
